[package]
name = "fastuuid-rs"
version = "0.1.0"
authors = ["pradovic <petar.radovic@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7.0"
atomic = "0.4.5"
faster-hex = "0.3.1"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "fastuuid_bench"
harness = false



